### ISSUE TITLE
Improve list filters

### ISSUE THREAD

**Issue by sjtrny** [sjtrny/forecast_dash#34]
For human readability we should be able to write URLs with filters in a comma separated format. However this introduces problems in parsing the URLs and updating them.

https://github.com/sjtrny/forecast_dash/commit/91626790ec0b3d700c7c12179a0d9a8bd15b567b#commitcomment-41271281

**Comment by david-houseman** [comment]
The prevailing opinion on the internet seems to be to urlencode an array of values in 'exploded' format

`/filter?methods=AAA&methods=BBB`

which can be parsed back to `methods = [ 'AAA', 'BBB' ]` using `parse_qs()`. The advantage of exploded format is that AAA and BBB can contain commas or other complicating characters.
