### ISSUE TITLE
Prevent re-forecasting for series that haven't changed

### ISSUE THREAD

**Issue by sjtrny** [sjtrny/forecast_dash#37]
> Another time-saving idea is for the forecasts pickle to cache a checksum (or hashsum) of the downloaded pickle. That way, if the downloaded pickle doesn't change, the checksums will match and the forecasts can be safely re-used without recomputing.

_Originally posted by @david-houseman in https://github.com/sjtrny/forecast_dash/issues/31#issuecomment-670328421_

**Comment by david-houseman** [comment]
In `hashsum` branch, re-using from caches completes in negligible time (<1s for whole script):

```
US GDP Growth
  - download: c55355f9f209361fef9712589f1100e6485285a6bacd4caf7bd3699e1db2576b
  - cache   : c55355f9f209361fef9712589f1100e6485285a6bacd4caf7bd3699e1db2576b
  - Re-using   : Naive
  - Re-using   : Theta
```

If the cache is not present or the hashsums don't match, all forecasts are re-computed:
```
US GDP Growth
  - download: c55355f9f209361fef9712589f1100e6485285a6bacd4caf7bd3699e1db2576b
  - cache   : Not found
  - Calculating: Naive
  - Calculating: Theta
```

```
US GDP Growth
  - download: c55355f9f209361fef9712589f1100e6485285a6bacd4caf7bd3699e1db2576b
  - cache   : 055355f9f209361fef9712589f1100e6485285a6bacd4caf7bd3699e1db2576b
  - Calculating: Naive
  - Calculating: Theta
```

When adding a modelling method, efficiently re-uses the cached forecasts that are available:
```
US GDP Growth
  - download: c55355f9f209361fef9712589f1100e6485285a6bacd4caf7bd3699e1db2576b
  - cache   : c55355f9f209361fef9712589f1100e6485285a6bacd4caf7bd3699e1db2576b
  - Re-using   : Naive
  - Re-using   : Theta
  - Calculating: Damped (ZZN, Damped)
```

To force re-calculation of all forecasts, simply delete the pickle/s in `data/forecasts/*.pkl`.
