### ISSUE TITLE
Fill out Methodology information

### ISSUE THREAD

**Issue by sjtrny** [sjtrny/forecast_dash#56]

**Comment by sjtrny** [comment]
Great, adding to meeting agenda with Andrey.

**Comment by robjhyndman** [comment]
Fine with me if you want to reproduce that image. I can provide the R code to generate it if you want it.

**Comment by sjtrny** [comment]
Thanks Rob!

**Comment by david-houseman** [comment]
Thanks Rob!

Stephen -- Merged in d187138. Feel free to amend the text if you like!
