### ISSUE TITLE
Add US macroeconomic indicators

### ISSUE THREAD

**Issue by sjtrny** [sjtrny/forecast_dash#7]
via FRED

**Comment by david-houseman** [comment]
FRED API:
https://fred.stlouisfed.org/docs/api/fred/

Sign up for an API key:
https://research.stlouisfed.org/docs/api/api_key.html

Available data formats:
https://fred.stlouisfed.org/docs/api/fred/series_observations.html
https://alfred.stlouisfed.org/help/downloaddata#outputformats
